/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import { Mesh } from 'three';
import { GLTF } from 'three-stdlib';
import suzanneModel from '@models/Suzanne.gltf';

type GLTFResult = GLTF & {
    nodes: {
        Suzanne: Mesh;
    };
    materials: {};
};

export function Suzanne(props: JSX.IntrinsicElements['group']) {
    // console.log(import.meta.resolve('./src/3DModels/Suzanne.gltf'));
    // console.log(fileURLToPath(new URL('./src/3DModels/', import.meta.url)));

    const { nodes, materials } = useGLTF(suzanneModel) as GLTFResult;
    // new URL('@models/Suzanne.gltf', import.meta.url).href

    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Suzanne.geometry}
                material={nodes.Suzanne.material}
                position={[0, 0.189, -0.043]}
            />
        </group>
    );
}

useGLTF.preload(suzanneModel);
