/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { useRef, useState } from 'react';
import poimandresModel from '@models/Poimandres.gltf';
import { useFrame } from '@react-three/fiber';

export default function Poimandres({ active = false, ...props }) {
    const groupRef = useRef(null);
    const { nodes, materials } = useGLTF(poimandresModel);

    // further away after each frames
    useFrame((state, delta) => {
        // groupRef.current.position.x += THREE.MathUtils.lerp(
        //     groupRef.current.position.x,
        //     active ? 100 : 0,
        //     0.1
        // );
    });

    return (
        <group ref={groupRef} {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve007_1.geometry}
                material={materials['Material.001']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curve007_2.geometry}
                material={materials['Material.002']}
            />
        </group>
    );
}

useGLTF.preload(poimandresModel);
